### ISSUE TITLE
Planificación 1.0

### ISSUE THREAD

**Issue by LorenzoSelas** [alru2002/ISO-II-C03#1]
https://github.com/alru2002/ISO-II-C03/wiki/Planificaci%C3%B3n-1.0 falta dar el ok por parte de @IsmaelCaballero o @fgualo

**Comment by fgualo** [comment]
Hay que indicar en la wiki los requisitos y casos de uso a cubrir en cada iteración. En cuanto esté, ok por mi parte

**Comment by LorenzoSelas** [comment]
Por favor, @fgualo revisa la planificación

**Comment by fgualo** [comment]
La planificación la veo bien, pero faltaría añadir a la wiki como parte de la iteración 0, listado de requisitos, casos de uso asociado a requisitos, diagrama de casos de uso general, y si queréis meter algo de control de versioenes de código de ramas master/main, una rama por iteración, etc.

**Comment by LorenzoSelas** [comment]
¿le parece cerrar la issue y añadir esto en la versión 1.1 de la planificación junto con el siguiente punto? @fgualo

**Comment by fgualo** [comment]
El diagrama de casos de uso general lo tendriais que añadir en la it00 de cara a la planificación 1.0. En la versión 1.1 de la planificación, podréis tocar todo lo que considereis a nivel de requsitos, casos de uso, horas, etc. cuando tengais que añadir los requisitos que decidais asoicados a las 3 características de calidad de producto software

**Comment by LorenzoSelas** [comment]
He añadido el diagrama de casos de uso general en la wiki, por favor, cuando puedas revísalo y dinos si falta algo o si habría que cambiar algo para poder continuar @fgualo

**Comment by fgualo** [comment]
ok por mi parte

**Comment by LorenzoSelas** [comment]
Perfecto, cierro la issue y empezamos con la revisión y el siguiente punto
