### ISSUE TITLE
Análisis Iteración 2

### ISSUE THREAD

**Issue by LorenzoSelas** [alru2002/ISO-II-C03#11]

**Comment by AlonsoHur** [comment]
Cliente
![image](https://user-images.githubusercontent.com/114938651/206171209-64689504-967d-409e-b6dd-64df2c425689.png)
![image](https://user-images.githubusercontent.com/114938651/206172780-40ba47e4-c077-4036-8923-9205912ded3f.png)

Servidor

![image](https://user-images.githubusercontent.com/114938651/206173146-55948ba8-7a15-4ef7-a1df-0954a5cafdcc.png)
![image](https://user-images.githubusercontent.com/114938651/206173040-c23b9346-0341-4c4d-b44f-c97b4e015755.png)

**Comment by alru2002** [comment]
En el de cliente en vez de IU_BBDD pon IU_Caminos

**Comment by AlonsoHur** [comment]
Cliente
![image](https://user-images.githubusercontent.com/114938651/206176879-7a2a1932-1503-43b8-bd72-53aa2023c5f3.png)
![image](https://user-images.githubusercontent.com/114938651/206176970-fc7a5ca1-469f-4f7a-9615-448dde8531ab.png)

server
![image](https://user-images.githubusercontent.com/114938651/206176837-ef1456d0-ad9d-436d-929d-840042776d02.png)
![image](https://user-images.githubusercontent.com/114938651/206177013-a13dcfea-1417-48e1-a4f0-246285c9032f.png)

**Comment by alru2002** [comment]
Todo ok

**Comment by AlonsoHur** [comment]
cierro issue con todo ok
