### ISSUE TITLE
Requisitos iteración 3

### ISSUE THREAD

**Issue by LorenzoSelas** [alru2002/ISO-II-C03#18]

**Comment by alru2002** [comment]
![image](https://user-images.githubusercontent.com/115723072/206435746-12974323-82c2-4fb0-a179-8c573dc8c8dc.png)

**Comment by alru2002** [comment]
![image](https://user-images.githubusercontent.com/115723072/206435949-466225f3-37b3-4644-8fec-3f25b45597c2.png)

**Comment by alru2002** [comment]
Requisitos terminados
