### ISSUE TITLE
Analisis iteración 3

### ISSUE THREAD

**Issue by LorenzoSelas** [alru2002/ISO-II-C03#19]

**Comment by pabloalmansa96** [comment]
Buenas tardes, aquí el análisis de la iteración 3:
![image](https://user-images.githubusercontent.com/115486474/206530559-e3c61bcb-c6d1-418d-9b2c-82451cd1459e.png)

Y servidor:

![image](https://user-images.githubusercontent.com/115486474/206530723-39d20481-c808-4d6b-a981-48da1d6e3960.png)
Espero que @alru2002 me de el visto bueno

**Comment by alru2002** [comment]
Haz 2 diagramas diferentes en vez los dos a la vez, la parte de arriba es un diagram y la parte de abajo es otro, tanto para el cliente como para el servidor

**Comment by pabloalmansa96** [comment]
Ya estaba en 2 diagramas, lo he unido para la foto

**Comment by alru2002** [comment]
Pues todo ok

**Comment by pabloalmansa96** [comment]
Gracias @alru2002
