### ISSUE TITLE
Diseño Iteración 3 

### ISSUE THREAD

**Issue by LorenzoSelas** [alru2002/ISO-II-C03#20]

**Comment by sanchezbarba** [comment]
Cliente
![image](https://user-images.githubusercontent.com/114937716/206547005-4e21c029-b4e9-477b-8640-0484aa5a05f7.png)
Servidor
![image](https://user-images.githubusercontent.com/114937716/206547116-947c63cb-c795-459a-aba6-f8b921f13713.png)

**Comment by sanchezbarba** [comment]
Se han implementado los diagramas de clases de diseño para la parte cliente y servidor. A la espera del ok para cerrar la issue @alru2002

**Comment by alru2002** [comment]
Perfecto
