### ISSUE TITLE
Requisitos Iteración 4

### ISSUE THREAD

**Issue by sanchezbarba** [alru2002/ISO-II-C03#24]

**Comment by sanchezbarba** [comment]
Cliente
![image](https://user-images.githubusercontent.com/114937716/206689343-7fc0f33d-66ec-4221-83bf-d792396d6f07.png)
Servidor
![image](https://user-images.githubusercontent.com/114937716/206689403-f0f1edd3-8900-4eb6-90d7-547141ab6b8b.png)

**Comment by sanchezbarba** [comment]
A la espera del ok, para hacer el commit y cerrar la issue.

**Comment by alru2002** [comment]
Todo ok
