### ISSUE TITLE
Análisis Iteración 4

### ISSUE THREAD

**Issue by sanchezbarba** [alru2002/ISO-II-C03#25]

**Comment by AlonsoHur** [comment]
servidor: 
![image](https://user-images.githubusercontent.com/114938651/206855844-08951036-e14e-4f10-b952-5265047c22d6.png)
![image](https://user-images.githubusercontent.com/114938651/206856091-15a81545-ff9b-4513-ac7d-5071154c7809.png)

cliente:
![image](https://user-images.githubusercontent.com/114938651/206855990-945d2cdb-72db-4587-a918-5375cfd0a06c.png)
![image](https://user-images.githubusercontent.com/114938651/206856045-e6e09f57-8b31-48a0-9227-36c44e2e0097.png)

todo ok?

**Comment by alru2002** [comment]
Ok
