### ISSUE TITLE
Requisitos it1

### ISSUE THREAD

**Issue by alru2002** [alru2002/ISO-II-C03#3]

**Comment by AlonsoHur** [comment]
![image](https://user-images.githubusercontent.com/114938651/203112518-da2f954d-ad9d-46c9-9a67-828388a8f0dc.png)

@alru2002 ok?

**Comment by AlonsoHur** [comment]
![image](https://user-images.githubusercontent.com/114938651/203116281-13d90a45-1ad6-4bd9-b1e6-51ca5b087642.png)

@alru2002 ok?

**Comment by alru2002** [comment]
todo Ok
