### ISSUE TITLE
Requisitos it5

### ISSUE THREAD

**Issue by alru2002** [alru2002/ISO-II-C03#30]

**Comment by LorenzoSelas** [comment]
![image](https://user-images.githubusercontent.com/73909685/207251027-f907ebfd-c6d2-40bd-8901-9e957d43756e.png)

análisis de requisitos de la iteración 5, falta ok por parte de @alru2002

**Comment by alru2002** [comment]
Haz otro con herramienta cliente y sube el paradygm

**Comment by alru2002** [comment]
todo Ok
