### ISSUE TITLE
Análisis it5

### ISSUE THREAD

**Issue by alru2002** [alru2002/ISO-II-C03#31]

**Comment by sanchezbarba** [comment]
Cliente
![image](https://user-images.githubusercontent.com/114937716/207373664-c1ccdbbd-72d5-41bb-9296-b10dc6be5457.png)
![image](https://user-images.githubusercontent.com/114937716/207373749-dd2ad929-1f04-41f8-9d2d-7e7952a6f298.png)
Servidor
![image](https://user-images.githubusercontent.com/114937716/207374180-b3741f05-9e0b-4698-9ace-5971cf0d24d8.png)
![image](https://user-images.githubusercontent.com/114937716/207374272-780acbd4-2348-4812-b4b1-dd631f032b5f.png)
