### ISSUE TITLE
Analisis Iteración 6

### ISSUE THREAD

**Issue by LorenzoSelas** [alru2002/ISO-II-C03#37]

**Comment by LorenzoSelas** [comment]
Diagrama Servidor:
![image](https://user-images.githubusercontent.com/73909685/207653359-722b6736-30e3-48e2-a62f-221397fea1ad.png)

Diagrama Cliente:
![image](https://user-images.githubusercontent.com/73909685/207653403-0072d8f3-8410-43ac-858c-3844e083e25f.png)

falta el ok por @alru2002

**Comment by alru2002** [comment]
ok

**Comment by alru2002** [comment]
Falta los de casos de uso

**Comment by LorenzoSelas** [comment]
![image](https://user-images.githubusercontent.com/73909685/207860796-bcf26ba3-056a-4d09-90f9-c6a4cbd7719e.png)
![image](https://user-images.githubusercontent.com/73909685/207860826-0daa598c-c041-4d52-abd1-6f288b3d1d8c.png)
@alru2002

**Comment by alru2002** [comment]
Cierro la issue porque lorenzo no esta disonible pesee a que ha hecho el el analisis
