### ISSUE TITLE
Diseño Iteración 6

### ISSUE THREAD

**Issue by LorenzoSelas** [alru2002/ISO-II-C03#38]

**Comment by AlonsoHur** [comment]
Cliente
![image](https://user-images.githubusercontent.com/114938651/207923179-343aace0-f278-423a-ac41-e2715ce6f8be.png)

Servidor
![image](https://user-images.githubusercontent.com/114938651/207923230-dca7a166-9f14-490e-8e8c-ad10e7ef02d9.png)
todo ok?

**Comment by alru2002** [comment]
al reves mejor

**Comment by AlonsoHur** [comment]
cliente
![image](https://user-images.githubusercontent.com/114938651/207923581-f91129e3-d37b-4f0e-99e3-e81ae430e94e.png)

servidor
![image](https://user-images.githubusercontent.com/114938651/207923730-cf15f2fb-b14f-4a8b-9ff4-fbf83fa8a805.png)

**Comment by alru2002** [comment]
ok
